

import React from "react";

export const categories = [
  {
    name: "Automotive",
    children: [
      {
        groupId:"A",
        name: "Automobile Related",
        children: [
          "Automobile Accessories",
          "Automobile Garage Related",
          "Automobile Maintanance Related",
          "Automobile Spares / Tyre",
          "Road Safety Equipments",
          "Security & Helpline Services",
          "Web Based/Online Platform",
        ],
      },
      {
        groupId:"B",
        name: "Commercial Vehicles",
        children: [
          "Commercial Vehicles Bus/Trucks",
          "Commercial Electric Vehicles (EV)",
          "Off Road / All Terrain Vehicles",
          "Three Wheeler (Auto) Showroom",
          "Tractors",
        ],
      },
      {
        groupId:"C",
        name: "Four Wheeler",
        children: [
          "Car Exterior Parts",
          "Car Interior Accessories",
          "Car Interior Spare Parts",
          "Car Maintanance & Repair Services",
          "Car Rental",
          "Car Reselling",
          "Car Showroom",
          "Car Wash / Ceramic Coating / Detailing",
          "Electric Vehicles Four Wheelers (EV)",
        ],
      },
      {
        groupId:"D",
        name: "Two Wheeler",
        children: [
          "Bicycle",
          "Bike Maintanance & Repair Services",
          "Bike Rental",
          "Bike Showroom",
          "Bike Wash",
          "Biker's Accessories",
          "Electric Vehicles Two Wheelers (EV)",
        ],
      },
    ],
  },
  {
    name: "Beauty & Health",
    children: [
      {
        groupId:"A",
        name: "Beauty Aesthetics & Supplies",
        children: [
          "Bath Products",
          "Beauty Equipments",
          "Beauty Salons/ Unisex Salons/ Spa",
          "Cosmetic Accessories",
          "Cosmetics & Beauty Product Stores",
          "Pet Grooming",
          "Tattoo, Piercing & Nail Art",
        ],
      },
      {
        groupId:"B",
        name: "Health Care",
        children: [
          "Ayurvedic & Herbal Products",
          "Fitness & Gym Equipments",
          "Fitness Centres",
          "Health & Wellness Centres",
          "Health Care Services",
          "Medical Equipment & Supplies",
          "Nutrition & Supplements",
          "Pharmacy",
        ],
      },
      {
        groupId:"C",
        name: "Wellness",
        children: [
          "Fitness & Gym Equipments",
          "Health & Wellness Centres",
          "Health Care Services",
          "Medical Equipment & Supplies",
          "Nutrition & Supplements",
          "Pharmacy",
        ],
      },
    ],
  },
  {
    name: "Business Services",
    children: [
      {
        groupId:"A",
        name: "Advertising & Marketing",
        children: [
          "Advertising & Marketing Agencies",
          "Digital Marketing",
          "Event Management",
          "Public Relations",
          "Social Media Marketing",
        ],
      },
      {
        groupId:"B",
        name: "Business Consulting",
        children: [
          "BPO",
          "Business",
          "Career Counseling",
          "Financial",
          "HR & Recruitment",
          "Immigration",
          "Legal",
          "Matrimonial",  
          "Others Consultancy",
          "Real Estate",
          "Service For SMEs",
          "Technology",
        ],
      },
      {
        groupId:"C",
        name: "Financial Services",
        children: [
          "Accounting & Auditing Services",
          "Equity & Debt Providers",
          "Finance Advisors & Brokers",
          "Financial Investment & Trading",
          "Foreign Exchange (FOREX)",
          "Insurance",
          "Microfinance",
          "Non Banking Financial Company (NBFC)",
          "Others Financial",
          "Payment Solution Services",
          "Post Office Services",
          "Tax Consulting Services",
          "Wealth Management",
        ],
      },
      {
        groupId:"D",
        name: "Household Services",
        children: [
          "Electrical & Plumbing Services",
          "Facility Management",
          "Gardening Services",
          "Home Appliances Repair Services",
          "Home Renovation Services",
          "Home Safety & Security",
          "Housekeeping",
          "Institutional/Facility Cleaning",
          "Laundry & Dry Cleaning",
          "Pest Control",
          "Repair Services",
        ],
      },
      {
        groupId:"E",
        name: "IT Services",
        children: [
          "Application Development",
          "Cloud Services",
          "Computer Hardware & Software",
          "Data Science & Analytics",
          "Domain & Hosting Services",
          "ERP Solutions",
          "IT Consulting",
          "IT Infrastructure Management",
          "Mobile App Development",
          "Networking & Security Services",
          "Software Development",
          "Web Development",
        ],
      },
      {
        groupId:"F",
        name: "Logistics & Transportation",
        children: [
          "Cargo & Freight Services",
          "Courier Services",
          "Freight Forwarding",
          "International Logistics",
          "Logistics Aggregators",
          "Packers & Movers",
          "Transportation",
        ],
      },
      {
        groupId:"G",
        name: "Real Estate",
        children: ["Commercial Real Estate", "Residential Real Estate"],
      },
      {
        groupId:"H",
        name: "Travel & Tourism",
        children: [
          "Adventure Tourism",
          "Air Ticketing Services",
          "Car Rentals",
          "Cruise Services",
          "Domestic Tour Operators",
          "Foreign Tour Operators",
          "Hotel & Resort Booking Services",
          "Railway Ticketing Services",
          "Travel Insurance",
        ],
      },
      {
        groupId:"I",
        name: "waste Management & Recycling",
        children: [
          "E-Waste Recycling",
          "Hazardous Waste Management",
          "Plastic Waste Management",
          "Waste Collection & Disposal",
          "Waste Recycling",
        ],
      },
    ],
  },
  {
    name: "Education & Training",
    children: [
      {
        groupId:"A",
        name: "Coaching & Tutoring",
        children: [
          "CAD/CAM/CAE & Multimedia",
          "Competitive Exam Coaching Institute",
          "Online Coaching",
          "Robotics & Technical Training/ AI",
          "School Tutoring",
        ],
      },
      {
        groupId:"B",
        name: "Early Education",
        children: ["Day Care", "Montessori Schools", "Preschools/Play Schools"],
      },
      {
        groupId:"C",
        name: "Education Consultants",
        children: ["Education Consultants", "Overseas Education Consultants"],
      },
      {
        groupId:"D",
        name: "Education Services",
        children: [
          "Education Services",
          "Educational Institutions",
          "Educational Software & Apps",
          "Online Learning Platforms",
        ],
      },
      {
        groupId:"E",
        name: "Higher Education",
        children: [
          "Degree/Diploma Colleges",
          "Distance Learning Centres",
          "Professional Education Colleges",
          "Universities (including Overseas Franchises)",
        ],
      },
      {
        groupId:"F",
        name: "online Learning",
        children: [
          "Certification Course Coaching",
          "Corporate Training",
          "Entrance Examination Coaching",
          "Foreign Language Coaching",
          "Online Learning/E-learning",
          "Other Online Education",
          "Professional Education Coaching",
        ],
      },
      {
        groupId:"G",
        name: "Vocational Training",
        children: [
          "Aviation & Hospitality Training Institute",
          "BPO/KPO Training Institutes",
          "Banking & Insurance Training Institute",
          "Beauty & Wellness Training Institute",
          "Financial Advisory",
          "HR Certification Institute",
          "IT Education",
          "Language Schools",
          "Other Vocational Training",
          "Paramedical/Medical Training",
          "Retail Training Institutes",
          "Skills / Personality Development",
        ],
      },
    ],
  },
  {
    name: "Fashion & Lifestyle",
    children: [
      {
        groupId:"A",
        name: "Accessories",
        children: [
          "Bags & Luggage",
          "Belt & Wallets",
          "Eyewear",
          "Fashion Accessories",
          "Footwear",
          "Jewellery",
          "Watches",
        ],
      },
      {
        groupId:"B",
        name: "Clothing",
        children: [
          "Apparel & Garments",
          "Clothing Accessories",
          "Fabric & Textile",
          "Footwear",
          "Garment Manufacturing",
          "Jewellery",
          "Leather Garments",
          "Textile Machinery & Equipment",
        ],
      },
      {
        groupId:"C",
        name: "Cosmetics & Beauty Products",
        children: [
          "Beauty & Personal Care",
          "Cosmetics & Beauty Products",
          "Cosmetics & Beauty Product Stores",
          "Health & Wellness Centres",
          "Medical Equipment & Supplies",
        ],
      },
    ],
  },
  {
    name: "Food & Beverages",
    children: [
      {
        groupId:"A",
        name: "Food Franchises",
        children: [
          "QSR (Quick Service Restaurants)",
          " Casual Dining",
          "Fine Dining",
          "Multi Cuisine Restaurants",
          "Indian / South Indian / North Indian",
          "Chinese / Pan-Asian",
          "Italian / Continental",
          "BBQ / Grills / Burgers / Pizza",
          "Vegan Restaurants",
          "Vegetarian-Only Restaurants",
          "Seafood-Based Restaurants",
        ],
      },
      {
        groupId:"B",
        name: "Beverage Franchises",
        children: ["Coffee & Tea Cafes",
           "Juice & Smoothie Bars",
           "Functional Beverages",
           "Alcoholic Beverage Lounges",
           "Bubble Tea",
           "Specialty Coffee Roasters",
           "Vegan Smoothie Brands",
           "Ayurvedic / Herbal Juices",
           "Kombucha / Probiotic Drinks",
           "Sports / Energy Beverages",
          ],
      },
      {  
        groupId:"C",
        name: "Dessert & Bakery",
        children: [
          "Bakeries & Patisseries",
          "Ice Cream & Frozen Dessert Parlors",
          "Chocolatiers",
          "Custom Cakes",
          "Artisanal Breads",
          "Frozen Yogurt / Gelato",
          "Vegan Cakes & Desserts",
          "Gluten-Free Desserts",
          "Indian Mithai / Fusion Sweets",
        ],
      },
      {
        groupId:"D",
        name: "Cloud Kitchens & Delivery",
        children: [
          "Multi-Brand Cloud Kitchens",
          "Niche Delivery Kitchens",
          "Virtual Restaurant Brands",
          "Indian Combo Kitchens",
          "Healthy Meal Plans",
          "Vegan Meal Delivery",
          "Dabba / Tiffin Services",
          "Biryani Specialists",
          "Global Cuisine Cloud Concepts",
        ],
      },
      {  
        groupId:"E",
        name: "Food Trucks & Kiosks Franchises",
        children: [
          "Street Food Vans",
          "Mall Food Kiosks",
          "Compact Beverage Counters",
          "South Indian Snacks",
          "Burger / Sandwich Counters",
          "Vegan Street Food",
          "Chaat Counters",
          "Corn / Popcorn / Ice Gola Stalls",
          
        ],
      },
      {
        groupId:"F",
        name: "Food Equipment & Machinery Franchises",
        children: [
          "Commercial Kitchen Equipment",
          "Bakery Equipment",
          "Cold Storage & Display",
          "Smart Automation & POS",
          "Food Packaging Machines",
          "Ovens / Fryers / Mixers",
          "Cold Press Juicers",
          "Composting / Waste Management",
          "Billing Machines / POS Systems",
          "Vacuum Packing / Sealing Machines",
          "Refrigeration & Cold Chain Equipment",
        ],
      },
      {
        groupId:"G",
        name: "Catering & Institutional Food ",
        children: [
          "Corporate & Institutional Catering",
          "School & College Catering",
          "Event & Outdoor Catering",
          "Hospital & Wellness Catering",
          "Veg Catering Services",
          "Buffet Setup Providers",
          "Industrial Meal Prep Kitchens",
          "Plant-Based Institutional Catering",
          "Community Kitchen Franchises",
        ],
      },
      {
        groupId:"H",
        name: "Organic, vegan & Health Foods",
        children: [
          "Vegan & Plant-Based Cafes",
          "Organic & Natural Food Brands",
          "Health-Focused Restaurants",
          "Diet/Nutrition Based Meal Services",
          "Immunity Boosting/Functional Foods",
          "Vegan Meal Plan Delivery",
          "Plant-Based Protein / Supplements Cafes",
          "Gluten-Free / Keto / Paleo Kitchens",
          "Ayurvedic / Herbal Food Kitchens",
          "Vegan Packaged Food & Snacks",
          "Clean Label / No Preservative Brands",
        ],
      },
      {
        groupId:"I",
        name: "Regional & Ethnic Cuisine",
        children: [
          "South Indian",
          "North Indian",
          "Bengali, Gujarati, Maharashtrian",
          "Chettinad / Kerala Cuisine",
          "Middle Eastern / Mediterranean",
          "Pan-Asian / Thai / Oriental",
          "Tandoori / Mughlai Kitchens",
          "Ethnic Veg Thali Concepts",
          "Vegan Fusion with Ethnic Cuisine",
          "Coastal Cuisine",
          "Tribal / Folk Food Concepts",
        ],
      },
      {
        groupId:"J",
        name: "F & B Franchise Stores",
        children: [
          "Grocery & Provisional Stores",
          "Fruits & Vegetables Outlets",
          "Organic & Natural Food Marts",
          "Dairy & Milk Product Stores",
          "Dry Fruits, Spices & Masalas",
          "Meat & Seafood Outlets",
          "Imported / Gourmet Food Stores",
          "Vegan & Plant-Based Grocery Stores",
          "Healthy & Diet Food Retail",
          "Kirana Store Format",
          "Hyperlocal Delivery Enabled",
          "Franchise Supermarket Chains",
          "Direct-from-Farm Concepts",
          "Cold Chain Store Concepts",
          "Subscription Model Grocery Stores",
          "Pre-Mixed / Ready-to-Cook Food Stores",
          "Ayurvedic / Herbal Food Retail",
          "Frozen Foods & Packaged Meat",
          "Dairy Chains (Milk, Curd, Paneer, Ice Cream)",
        ],
      },
      // {
      //   name: "Restaurant & Night Clubs",
      //   children: [
      //     "Casual Dine Restaurants",
      //     "Fine Dine Restaurants",
      //     "Multi Cuisine Restaurant",
      //     "Theme Restaurants",
      //     "Bars, Pubs & Lounge",

      //   ],
      // },
      //  {
      //   name: "Cafe & Parlors",
      //   children: [
      //     "Cafe Shops",
      //     "Juices", "Smoothies"," Dairy Parlors",
      //     "Tea And Coffee Chain",
      //   ],
      // },
      //  {
      //   name: "Services",
      //   children: [
      //     "Food Delivery ",
      //     "catering ",
          
      //   ],
      // },
      //  {
      //   name: "Food Equipment",
      //   children: [
          
      //     " Kitchen Equipment ",
      //     "food Preparation Equipment ",
      //     "Bakery Equipment ",
        
      //   ],
      // },
      //  {
      //   name: "Food Products",
      //   children: [
      //     "Provession Stores",
      //     "Meat Shops",
      //     "Fruits & Vegetables",
      //   ],
      // },
      // {
      //   name: "Bakery, Sweets & Ice Cream",
      //   children: [
      //     "Bakery & Confectionary",
      //     " Chocolate Stores",
      //     "Snacks / Namkeen Shops",
      //     "Sweetshop",
      //     "Ice Creams & Yogurt Parlors",
      //   ],
      // },
      // {
      //   name: "Catering & Food Services",
      //   children: ["Catering Service", "Online Food Ordering Services"],
      // },
     
      // {
      //   name: "Food & Beverage",
      //   children: [
      //     "Beverages",
      //     "Hotel Equipment and Supplier",
      //     "Others Food Service",
      //   ],
      // },
      
      
    ],
  },
  {
    name: "HomeBased Business Services",
    children: [
      {
        groupId:"A",
        name: "Beauty & Personal Care",
        children: [
          "Beauty & Personal Care",
          "Cosmetics & Beauty Products",
          "Cosmetics & Beauty Product Stores",
          "Health & Wellness Centres",
          "Medical Equipment & Supplies",
        ],
      },
      {
        groupId:"B",
        name: "Business Services",
        children: [
          "Accounting & Auditing Services",
          "Equity & Debt Providers",
          "Finance Advisors & Brokers",
          "Financial Investment & Trading",
          "Foreign Exchange (FOREX)",
          "Insurance",
          "Microfinance",
          "Non Banking Financial Company (NBFC)",
          "Others Financial",
          "Payment Solution Services",
          "Post Office Services",
          "Tax Consulting Services",
          "Wealth Management",
        ],
      },
      {
        groupId:"C",
        name: "repair & Maintenance",
        children: [
          "Electrical & Plumbing Services",
          "Facility Management",
          "Gardening Services",
          "Home Appliances Repair Services",
          "Home Renovation Services",
          "Home Safety & Security",
          "Housekeeping",
          "Institutional/Facility Cleaning",
          "Laundry & Dry Cleaning",
          "Pest Control",
          "Repair Services",
        ],
      },
      {
        groupId:"D",
        name: "technology & Releated",
        children: [
          "Application Development",
          "Cloud Services",
          "Computer Hardware & Software",
          "Data Science & Analytics",
          "Domain & Hosting Services",
          "ERP Solutions",
          "IT Consulting",
          "IT Infrastructure Management",
          "Mobile App Development",
          "Networking & Security Services",
          "Software Development",
          "Web Development",
        ],
      },
    ],
  },
  {
    name: "Hotels & Resorts",
    children: [
      {
        groupId:"A",
        name: "Hotels",
        children: ["Hotel Booking Services", "Hotels & Resorts"],
      },
      {
        groupId:"B",
        name: "Resorts",
        children: ["Hotel Booking Services", "Hotels & Resorts"],
      },
      {
        groupId:"C",
        name: "Travel & Tourism",
        children: [
          "Adventure Tourism",
          "Air Ticketing Services",
          "Car Rentals",
          "Cruise Services",
          "Domestic Tour Operators",
          "Foreign Tour Operators",
          "Hotel & Resort Booking Services",
          "Railway Ticketing Services",
          "Travel Insurance",
        ],
      },
      {
        groupId:"D",
        name: "Travel Agents",
        children: ["Travel Agents", "Travel Booking Services"],
      },
    ],
  },
  {
    name: "Retails",
    children: [
      {
        groupId:"A",
        name: "Books & Stationery",
        children: ["Books & Stationery", "Books & Stationery Stores"],
      },
      {
        groupId:"B",
        name: "consumer Durables",
        children: [
          "Consumer Electronics",
          "Consumer Electronics Stores",
          "Consumer Goods",
          "Consumer Goods Stores",
        ],
      },
      {
        groupId:"C",
        name: "E-Retail",
        children: ["E-Commerce", "E-Commerce Stores"],
      },
      {
        groupId:"D",
        name: "Fashion",
        children: [
          "Apparel & Garments",
          "Clothing Accessories",
          "Fabric & Textile",
          "Footwear",
          "Garment Manufacturing",
          "Jewellery",
          "Leather Garments",
          "Textile Machinery & Equipment",
        ],
      },
      {
        groupId:"E",
        name: "Home & Office",
        children: [
          "Home & Office Appliances",
          "Home & Office Appliances Stores",
        ],
      },
      {
        groupId:"F",
        name: "supermarket & Grocery",
        children: [
          "Dairy/F&V Stores",
          "Department & Convenience Stores",
          "Food Marts",
          "Gourmet Stores",
          "Grocery Stores",
          "Kiosks",
          "Meat & Chicken Shops",
          "Organic Products",
          "Pet Stores",
          "Superstores",
          "Wine Shops",
        ],
      },
    ],
  },
  {
    name: "Sports & Fitness & Entertainment",
    children: [
      {
        groupId:"A",
        name: "Fitness & Gym",
        children: [
          "Fitness & Gym Equipments",
          "Fitness Centres",
          "Health & Wellness Centres",
          "Health Care Services",
          "Medical Equipment & Supplies",
          "Nutrition & Supplements",
          "Pharmacy",
        ],
      },
      {
        groupId:"B",
        name: "Sports & Games",
        children: [
          "Sports & Games Accessories",
          "Sports & Games Equipments",
          "Sports & Games Stores",
        ],
      },
      {
        groupId:"C",
        name: "entertainment",
        children: [
          "Event Management",
          "Event Organizers",
          "Event Planning",
          "Event Production",
          "Event Rentals",
        ],
      },
    ],
  },
];

export default categories;

